--------------------------------------------------------------------- 1. changed yocto project version from warrior to dunfell 2. applied to the latest version    original git repository : git://git.yoctoproject.org/meta-raspberrypi
Last Commit
commit 987993209716302eb8f314f69a2a3340555f94d8 (HEAD -> dunfell, origin/dunfell)
Author: Martin Jansa <Martin.Jansa@gmail.com>
Date:   Fri Nov 6 22:05:16 2020 +0100

    Revert "libcamera: Define packageconfig to enable rpi pipeline"

    This reverts commit a27f10b76cb1dbf089a3f0980e97f1931b090f17.

    This was backported to dunfell together with many other changes in:
    https://github.com/agherzan/meta-raspberrypi/pull/754

    but 202002 version in dunfell fails with:
    ERROR: QA Issue: libcamera: configure was passed unrecognised options: pipelines [unknown-configure-option]

    202008 version in gatesgarth is fine, it was added in March:
    https://git.linuxtv.org/libcamera.git/commit/meson_options.txt?id=ee7e2c93dfbf34b3500c895115c516e5e90d3e31

    Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

---------------------------------------------------------------------